# Generated by Django 3.2.9 on 2021-11-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
