# Generated by Django 3.2.9 on 2021-11-30 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by_verifications', to=settings.AUTH_USER_MODEL)),
                ('verified_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_user_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_note', models.TextField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_requested_by', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_requested_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permitted_by_permissions', to=settings.AUTH_USER_MODEL)),
                ('permitted_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permitted_user_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_note', models.TextField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_requested_by', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_requested_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
