# Generated by Django 3.2.9 on 2021-11-30 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
        ('user_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_request',
            name='requested_to',
        ),
        migrations.RemoveField(
            model_name='contact_request',
            name='requested_to',
        ),
        migrations.AddField(
            model_name='complaint_request',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_request', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaint_request',
            name='requested_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_requested_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact_request',
            name='requested_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_requested_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verification',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verification',
            name='verified_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
