# Generated by Django 3.2.9 on 2022-01-16 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0003_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_request',
            name='request_note',
        ),
    ]
