# Generated by Django 3.2.8 on 2021-10-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211023_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
