# Generated by Django 3.2.8 on 2021-10-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_complaint_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='tags',
        ),
    ]
