# Generated by Django 3.2.8 on 2021-10-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_complaint_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='place',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
