# Generated by Django 3.2.8 on 2021-10-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_complaint_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='request_image',
            field=models.ImageField(blank=True, default='complaints/default-image.jpg', null=True, upload_to='complaints'),
        ),
    ]
