# Generated by Django 3.2.9 on 2021-11-05 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_complaint_request_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='updates',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(default='comment', max_length=50)),
                ('message_content', models.CharField(max_length=1000, null=True)),
                ('message_complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.complaint')),
                ('message_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
