# Generated by Django 3.2.9 on 2021-11-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211105_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='description',
            new_name='complaint_description',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='place',
            new_name='complaint_place',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='request_image',
            new_name='complaint_request_image',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='status',
            new_name='complaint_status',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='title',
            new_name='complaint_title',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='under_investigation_by',
            new_name='complaint_under_investigation_by',
        ),
    ]
