# Generated by Django 3.2.9 on 2021-11-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_documents',
            field=models.ImageField(null=True, upload_to='identity'),
        ),
    ]
