# Generated by Django 3.2.9 on 2021-11-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_identity_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Normal user/Victim', 'Normal user/Victim'), ('NGO/Activist/Mod', 'NGO/Activist/Mod')], max_length=50, null=True),
        ),
    ]
