# Generated by Django 3.2.9 on 2021-11-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='user_description',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='other',
            new_name='user_other',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='user_phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='user_profile_image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='user_role',
        ),
    ]
