# Generated by Django 3.2.9 on 2021-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211111_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Documents',
            new_name='User_Document',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
