# Generated by Django 3.2.9 on 2021-11-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20211111_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_complaint',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_user',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
