# Generated by Django 3.2.9 on 2021-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(default='profiles/default-image.jpg', null=True, upload_to='profiles'),
        ),
    ]
