# Generated by Django 3.2.9 on 2021-11-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_document',
            old_name='user_files',
            new_name='user_file',
        ),
        migrations.AddField(
            model_name='user_document',
            name='user_file_thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='identity_thumbnail'),
        ),
    ]
