# Generated by Django 3.2.9 on 2021-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20211120_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_document',
            name='user_file_thumbnail',
            field=models.ImageField(default='profiles/default-image.jpg', null=True, upload_to='profiles'),
        ),
    ]
