# Generated by Django 3.2.9 on 2021-11-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_user_document_user_file_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_verified_by',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
