# Generated by Django 3.2.9 on 2021-11-22 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_user_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_verified_by',
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to=settings.AUTH_USER_MODEL)),
                ('verified_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
