# Generated by Django 3.2.9 on 2021-11-27 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_contact_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_requests',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact_requests',
            name='requested_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_to_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_document',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verification',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verification',
            name='verified_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_user_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
