# Generated by Django 3.2.9 on 2021-11-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20211128_0130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Requests',
            new_name='Contact_Request',
        ),
    ]
