# Generated by Django 3.2.9 on 2021-11-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20211129_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_request',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='contact_request',
            name='requested_to',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='verified_user',
        ),
        migrations.DeleteModel(
            name='Contact_Permission',
        ),
        migrations.DeleteModel(
            name='Contact_Request',
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
