# Generated by Django 3.2.9 on 2022-01-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20211130_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='some string', max_length=100, unique=True),
        ),
    ]
