# Generated by Django 3.2.9 on 2021-11-11 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=1000, null=True)),
                ('complaint_description', models.TextField(null=True)),
                ('complaint_status', models.CharField(default='active', max_length=10)),
                ('complaint_request_image', models.ImageField(blank=True, default='complaints/default-image.jpg', null=True, upload_to='complaints')),
                ('complaint_place', models.CharField(max_length=1000, null=True)),
                ('complaint_under_investigation_by', models.CharField(blank=True, max_length=1000, null=True)),
                ('complaint_filer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(default='comment', max_length=50)),
                ('message_content', models.CharField(max_length=1000, null=True)),
                ('message_complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
                ('message_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
