# Generated by Django 3.2.9 on 2022-01-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20220111_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
